<?php
/** @var Magento\Wishlist\Block\Customer\Sidebar $block */
?>
<?php
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
?>
<?php if ($wishlistHelper->isAllow()): ?>
<!-- ko if: wishlist().counter -->
<!-- ko foreach: wishlist().items -->
<li class="product-item">
    <div class="product-item-info">
        <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
            <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
        </a>
        <div class="product-item-details">
            <strong class="product-item-name">
                <a data-bind="attr: { href: product_url }" class="product-item-link">
                    <span data-bind="html: product_name"></span>
                </a>
            </strong>
            <div data-bind="html: product_price"></div>
        </div>
        <div class="product-item-actions">
            <!-- ko if: product_is_saleable_and_visible -->
            <div class="actions-primary">
                <!-- ko if: product_has_required_options -->
                <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </a>
                <!-- /ko -->
                <!-- ko ifnot: product_has_required_options -->
                <button type="button"
                        class="action tocart primary"
                        data-bind="attr: {'data-post': add_to_cart_params}">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
                <!-- /ko -->
            </div>
            <!-- /ko -->
            <div class="actions-secondary">
                <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                   title="<?= $block->escapeHtmlAttr(__('Remove This Item')) ?>"
                   class="btn-remove action delete">
                    <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                </a>
            </div>
        </div>
    </div>
</li>
<!-- /ko -->
<li class="actions-toolbar">
    <a class="action details"
       href="<?= $block->escapeUrl($this->helper(\Magento\Wishlist\Helper\Data::class)->getListUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Go to Wish List')) ?>">
        <span><?= $block->escapeHtml(__('Go to Wish List')) ?></span>
    </a>
</li>
<!-- /ko -->
<!-- ko ifnot: wishlist().counter -->
<div class="empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
<!-- /ko -->
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>
<?php endif ?>
